#!/usr/bin/env python3
"""
analyze_robustness.py — the robustness analyses a reviewer will ask for, none of which were
in the original pre-registration. Companion to analyze_sweep.py.

Run:  python receipts/analysis/analyze_robustness.py

Sections:
  A. Run-to-run outcome instability (stretchA vs stretchB, 300 aligned episodes).
     The strongest available quantification of the non-determinism finding — far stronger
     than the n=6 determinism probe, because it is 300 paired episodes under identical
     settings on an identical driver.
  B. Differential compute censoring. Episodes are killed at a FIXED 900 s wall-clock. Arms
     that render slower hit that wall more often, and a wall_timeout forces SR=0. If the
     timeout rate differs by arm, part of any SR difference is a compute artifact rather
     than navigation behaviour. Reported with an ITT vs per-protocol sensitivity analysis.
  C. Reach/stop decomposition: OS is "got within the goal radius at some point", SR is
     "chose to stop there". Splitting them separates *navigation* from *arrival
     recognition* and is the only way to check the FOV mechanism claim.
  D. Scene stratification + cluster-robust CIs. Episodes cluster within a handful of MP3D
     scenes; episode-level binomial CIs assume independence and are anti-conservative.

Also writes episode_index.csv — a derived (episode_id, record_idx, scene, goal_radius) map,
which is what makes "episodes 0-299" interpretable to anyone outside this machine.
"""

import csv
import glob
import gzip
import hashlib
import json
import os
from collections import Counter, defaultdict

import numpy as np
from scipy import stats

HERE = os.path.dirname(os.path.abspath(__file__))
RECEIPTS = os.path.dirname(HERE)
ROOT = os.path.dirname(RECEIPTS)
DATASET = os.path.join(
    ROOT, "NaVILA-Bench-main/isaaclab_exts/omni.isaac.vlnce/assets/vln_ce_isaac_v1.json.gz")

TRANSFORM = [("stretchA", "stretchA_300"), ("stretchB", "stretchB_300"),
             ("crop", "crop_300"), ("pad", "pad_300")]
HEIGHT = [("h060", "h060_200"), ("h078", "h078_200"), ("h095", "h095_200"),
          ("h110", "h110_200"), ("h130", "h130_200"), ("h150", "h150_200")]

RNG = np.random.default_rng(20260822)   # fixed seed: the bootstrap is reproducible


def load(subdir):
    d = {}
    for f in glob.glob(os.path.join(RECEIPTS, "sweep_measurements", subdir, "*.json")):
        d[int(os.path.basename(f)[:-5])] = json.load(open(f))
    return d


def succ(r):
    return r.get("success", 0.0) >= 0.5


def osucc(r):
    return r.get("oracle_success", 0.0) >= 0.5


def wilson(k, n, alpha=0.05):
    if n == 0:
        return (float("nan"), float("nan"))
    z = stats.norm.ppf(1 - alpha / 2)
    p = k / n
    den = 1 + z * z / n
    c = (p + z * z / (2 * n)) / den
    h = z * np.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / den
    return (max(0, c - h), min(1, c + h))


def two_prop(k1, n1, k2, n2):
    p1, p2 = k1 / n1, k2 / n2
    pp = (k1 + k2) / (n1 + n2)
    se = np.sqrt(pp * (1 - pp) * (1 / n1 + 1 / n2))
    z = (p1 - p2) / se if se > 0 else 0.0
    p = 2 * (1 - stats.norm.cdf(abs(z)))
    pf = stats.fisher_exact([[k1, n1 - k1], [k2, n2 - k2]])[1]
    return (p1 - p2) * 100, z, p, pf


def main():
    out = []
    W = out.append
    arms = {tag: load(sub) for tag, sub in TRANSFORM + HEIGHT}

    W("# ROBUSTNESS ANALYSES — sweep\n")
    W("Generated by `receipts/analysis/analyze_robustness.py` from the committed receipts.")
    W("These analyses were NOT pre-registered. They are reported because a reviewer will ask")
    W("for them, and because two of them materially qualify the headline numbers. Treat")
    W("everything here as exploratory.\n")

    # ------------------------------------------------------------------ A
    W("\n## A. Run-to-run outcome instability (the non-determinism finding, quantified)\n")
    A, B = arms["stretchA"], arms["stretchB"]
    both = sorted(set(A) & set(B))
    n = len(both)
    a1b1 = sum(1 for k in both if succ(A[k]) and succ(B[k]))
    a1b0 = sum(1 for k in both if succ(A[k]) and not succ(B[k]))
    a0b1 = sum(1 for k in both if not succ(A[k]) and succ(B[k]))
    a0b0 = sum(1 for k in both if not succ(A[k]) and not succ(B[k]))
    disc = a1b0 + a0b1
    po = (a1b1 + a0b0) / n
    pe = ((a1b1 + a1b0) / n) * ((a1b1 + a0b1) / n) + ((a0b1 + a0b0) / n) * ((a1b0 + a0b0) / n)
    kappa = (po - pe) / (1 - pe)
    ever = a1b1 + a1b0 + a0b1

    W("`stretchA` and `stretchB` are the SAME 300 episodes, the same settings, the same")
    W("driver, the same weights. Every difference below is pure run-to-run noise.\n")
    W("| | B success | B failure |")
    W("|---|---|---|")
    W(f"| **A success** | {a1b1} | {a1b0} |")
    W(f"| **A failure** | {a0b1} | {a0b0} |")
    W(f"\n- Aggregate SR is nearly identical: {100*(a1b1+a1b0)/n:.1f}% vs {100*(a1b1+a0b1)/n:.1f}%")
    W(f"- **Per-episode outcomes are not:** {disc}/{n} = **{100*disc/n:.1f}% discordant**")
    W(f"- Cohen's kappa = **{kappa:.3f}** (moderate agreement only)")
    W(f"- Of the {ever} episodes that succeeded in *either* run, only {a1b1} "
      f"(**{100*a1b1/ever:.0f}%**) succeeded in *both*")
    mcn = stats.binomtest(a1b0, disc, 0.5).pvalue
    W(f"- McNemar exact on the discordant pairs: p = {mcn:.3f} (no directional bias — "
      f"as expected, since the two arms are the same condition)\n")
    W("**Why this matters for the paper.** The aggregate rate is reproducible; the per-episode")
    W("outcome is not. Roughly half of this benchmark's successes are coin-flips at the")
    W("episode level. This is the single most defensible statement of the non-determinism")
    W("finding, it rests on 300 episodes rather than the 6-episode probe, and it independently")
    W("justifies abandoning McNemar as the primary test (Amendment 1): a paired test on an")
    W("unstable pair measures noise.")

    # ------------------------------------------------------------------ B
    W("\n\n## B. Differential compute censoring (a real confound — must be reported)\n")
    W("The runner kills every episode at a FIXED **900 s wall-clock** and records it as a")
    W("failure (`term_reason=wall_timeout`, SR and SPL forced to 0). This is a *compute*")
    W("limit, not a navigation outcome. If arms render at different speeds, they hit the wall")
    W("at different rates, and SR is penalised for being slow rather than for being lost.\n")
    W("| arm | n | wall_timeout | rate | ITT SR % | per-protocol SR % | shift |")
    W("|---|---|---|---|---|---|---|")
    rows = {}
    for tag, _ in TRANSFORM + HEIGHT:
        d = arms[tag]
        wt = sum(1 for r in d.values() if r.get("term_reason") == "wall_timeout")
        keep = [r for r in d.values() if r.get("term_reason") != "wall_timeout"]
        itt = 100 * sum(1 for r in d.values() if succ(r)) / len(d)
        pp = 100 * sum(1 for r in keep if succ(r)) / len(keep)
        rows[tag] = (wt, len(d), itt, pp)
        W(f"| {tag} | {len(d)} | {wt} | {100*wt/len(d):.1f}% | {itt:.1f} | {pp:.1f} "
          f"| {pp-itt:+.1f} pp |")

    wc, nc, _, _ = rows["crop"]
    wp, np_, _, _ = rows["pad"]
    d_pp, z, pz, pf = two_prop(wc, nc, wp, np_)
    W(f"\n**The rates are not equal.** crop {100*wc/nc:.1f}% vs pad {100*wp/np_:.1f}%: "
      f"difference {d_pp:+.1f} pp, z = {z:.2f}, Fisher p = {pf:.2g}. That is far more")
    W("significant than any SR difference in the entire sweep.\n")
    itt_gap = rows["crop"][2] - rows["pad"][2]
    pp_gap = rows["crop"][3] - rows["pad"][3]
    W(f"**Sensitivity.** The crop-vs-pad SR gap is {itt_gap:+.1f} pp under intention-to-treat "
      f"but only {pp_gap:+.1f} pp once timed-out episodes are dropped — i.e. roughly "
      f"{100*(1-pp_gap/itt_gap):.0f}% of that gap is a compute artifact, not behaviour.")
    W("Neither gap is statistically significant, so no conclusion changes. But the ITT number")
    W("must not be presented as a pure behavioural difference.\n")
    W("**Caveat on the per-protocol column:** dropping timed-out episodes is itself biased —")
    W("slow episodes are plausibly the hard ones, so removing them inflates SR for every arm")
    W("(every shift above is positive). Report both columns and claim neither as the truth.")
    W("The clean fix is a compute budget defined in *simulation steps* rather than wall-clock;")
    W("`step_cap` already provides one, and a future sweep should rely on it alone.")

    # ------------------------------------------------------------------ C
    W("\n\n## C. Reach vs. arrival recognition\n")
    W("OS = reached the goal radius at some point. SR = *stopped* there. The conditional")
    W("SR|OS therefore isolates arrival recognition from navigation.\n")
    W("| arm | OS % (reached) | SR % (stopped) | SR given reached | 95% CI |")
    W("|---|---|---|---|---|")
    cond = {}
    for tag, _ in TRANSFORM + HEIGHT:
        d = arms[tag]
        reached = [r for r in d.values() if osucc(r)]
        st = sum(1 for r in reached if succ(r))
        lo, hi = wilson(st, len(reached))
        cond[tag] = (st, len(reached))
        W(f"| {tag} | {100*len(reached)/len(d):.1f} "
          f"| {100*sum(1 for r in d.values() if succ(r))/len(d):.1f} "
          f"| **{100*st/len(reached):.1f}%** | [{100*lo:.1f}, {100*hi:.1f}] |")

    sc, nc2 = cond["crop"]
    ss = cond["stretchA"][0] + cond["stretchB"][0]
    ns = cond["stretchA"][1] + cond["stretchB"][1]
    dd, z2, pz2, pf2 = two_prop(sc, nc2, ss, ns)
    W(f"\n**This REFUTES a claim currently in `FINAL_RESULTS_full1077.md` and `SLIDE_FACTS.md`.**")
    W("Those documents state, from an n=10 pilot, that *crop reached the goal but never")
    W("stopped*, and conclude that peripheral field-of-view is required for arrival")
    W("recognition. At n=300 the effect runs the other way:\n")
    W(f"- crop converts **{100*sc/nc2:.1f}%** of reaches into stops")
    W(f"- stretch (A+B pooled, n={ns}) converts **{100*ss/ns:.1f}%**")
    W(f"- difference {dd:+.1f} pp, Fisher p = {pf2:.3f}")
    W("\ncrop *reaches* less often (OS 24.0% vs 29.0/31.7%) but *recognises arrival better*")
    W("when it does. The pilot's direction did not replicate. The FOV-for-arrival-recognition")
    W("mechanism must be retracted from those two documents before the paper reuses it; the")
    W("honest n=300 statement is that no transform shows a significant SR difference, and the")
    W("reach/recognise split is exploratory and unpowered.")

    # ------------------------------------------------------------------ D
    W("\n\n## D. Scene clustering and cluster-robust intervals\n")
    if not os.path.exists(DATASET):
        W("Dataset not found; scene stratification skipped.")
    else:
        raw = open(DATASET, "rb").read()
        W(f"Episode dataset `vln_ce_isaac_v1.json.gz`, SHA-256 `{hashlib.sha256(raw).hexdigest()}`.")
        data = json.loads(gzip.decompress(raw))
        eps = data["episodes"] if isinstance(data, dict) else data
        scene_of, radius_of = {}, {}
        index_rows = []
        for order, e in enumerate(eps):
            rec = int(e["episode_id"]) - 1     # the eval names records episode_id - 1
            sc_name = e["scene_id"].split("/")[1]
            scene_of[rec] = sc_name
            radius_of[rec] = e.get("goals", [{}])[0].get("radius")
            index_rows.append({"list_order": order, "episode_id": e["episode_id"],
                               "record_idx": rec, "scene": sc_name,
                               "goal_radius": radius_of[rec]})
        with open(os.path.join(HERE, "episode_index.csv"), "w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=list(index_rows[0].keys()))
            w.writeheader()
            w.writerows(index_rows)

        radii = set(radius_of.values())
        W(f"All {len(eps)} episodes use goal radius {radii} m (dataset-supplied, not a")
        W("project constant). Derived `episode_index.csv` maps list order -> episode_id ->")
        W("record index -> scene, which is what makes \"episodes 0-299\" interpretable.\n")

        pinned = set(arms["stretchA"])
        allsc = Counter(scene_of[k] for k in scene_of)
        pinsc = Counter(scene_of[k] for k in pinned)
        W(f"The full benchmark spans **{len(allsc)} scenes**; the pinned 300 covers "
          f"**{len(pinsc)}**.\n")
        W("| scene | full set | share | pinned 300 | share | stretchA SR |")
        W("|---|---|---|---|---|---|")
        for s, c in allsc.most_common():
            inp = pinsc.get(s, 0)
            if inp:
                ks = [k for k in pinned if scene_of[k] == s]
                sr = f"{100*sum(1 for k in ks if succ(arms['stretchA'][k]))/len(ks):.1f}%"
            else:
                sr = "—"
            W(f"| {s} | {c} | {100*c/len(scene_of):.1f}% | {inp} | "
              f"{100*inp/len(pinned):.1f}% | {sr} |")

        W("\n**Two problems this creates.**\n")
        W("1. *The pinned subset is not scene-representative.* Several scenes are absent")
        W("   entirely and the surviving mix is reweighted. `PRE_REGISTRATION.md` asserts the")
        W("   0-299 subset is representative on marginal SR/OS alone; that is true of the")
        W("   margins and false of the composition. Since per-scene SR ranges from 0% to over")
        W("   40%, the margins agreeing is partly coincidence.")
        W("2. *Episode-level CIs are anti-conservative.* Episodes within a scene share a map,")
        W("   so they are not independent draws. Below, a **cluster bootstrap over scenes**")
        W("   (10,000 resamples, seed 20260822) replaces the binomial interval.\n")

        W("| arm | SR % | binomial 95% CI | scene-cluster 95% CI | width ratio |")
        W("|---|---|---|---|---|")
        for tag, _ in TRANSFORM + HEIGHT:
            d = arms[tag]
            byscene = defaultdict(list)
            for k, r in d.items():
                byscene[scene_of[k]].append(succ(r))
            keys = list(byscene)
            obs = 100 * sum(sum(v) for v in byscene.values()) / len(d)
            boot = []
            for _ in range(10000):
                pick = RNG.choice(len(keys), size=len(keys), replace=True)
                vals = [x for i in pick for x in byscene[keys[i]]]
                boot.append(100 * sum(vals) / len(vals))
            clo, chi = np.percentile(boot, [2.5, 97.5])
            k_ = sum(1 for r in d.values() if succ(r))
            blo, bhi = wilson(k_, len(d))
            blo, bhi = 100 * blo, 100 * bhi
            W(f"| {tag} | {obs:.1f} | [{blo:.1f}, {bhi:.1f}] | [{clo:.1f}, {chi:.1f}] "
              f"| {(chi-clo)/(bhi-blo):.2f}x |")
        W("\nWhere the cluster interval is materially wider, the binomial CI in ANALYSIS.md")
        W("overstates precision. Since every headline contrast is already null, wider")
        W("intervals do not change any conclusion — they *strengthen* the null. But the paper")
        W("should quote the cluster-robust intervals, or state plainly that intervals are")
        W("episode-level and ignore scene clustering.")

    # ------------------------------------------------------------------ schema note
    W("\n\n## E. Record-schema anomaly (small, but disclose it)\n")
    bad = []
    for tag, sub in TRANSFORM + HEIGHT:
        c = sum(1 for r in arms[tag].values() if r.get("max_episode_steps") == -1)
        if c:
            bad.append((tag, c))
    W(f"{sum(c for _, c in bad)} records across "
      f"{', '.join(f'{t} ({c})' for t, c in bad)} carry `max_episode_steps = -1` and")
    W("`ended_at_step = -1`. These come from the **runner-side** wall-timeout stub in")
    W("`run_powered_benchmark.sh`, not the in-eval SIGTERM handler, so two writers with")
    W("slightly different schemas both produced records in this dataset. Scoring is")
    W("unaffected (SR/SPL are 0 either way and the distance sentinel is handled identically),")
    W("but any analysis of `ended_at_step` must exclude the -1 rows. ANALYSIS.md §5 currently")
    W("includes them in the step means; with 9 rows out of 2,400 the effect is negligible,")
    W("and it is noted here rather than silently fixed.")

    report = "\n".join(out) + "\n"
    with open(os.path.join(HERE, "ROBUSTNESS.md"), "w") as f:
        f.write(report)
    print(report)
    print(f"\nwrote: {HERE}/ROBUSTNESS.md and episode_index.csv")


if __name__ == "__main__":
    main()
